# Generated by Django 3.1.6 on 2021-03-18 09:22

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=50, verbose_name='Hakkımızda Resim Ortası Başlık')),
                ('about_main_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Hakkımızda Ana Resim')),
                ('images_title', models.CharField(max_length=50, verbose_name='Hakkımızda Resimler Başlık')),
                ('images_content', models.TextField(max_length=50, verbose_name='Hakkımızda Resimler İçerik')),
                ('youtube_url', models.URLField(verbose_name='Hakkımızda Video Linki')),
                ('button_name', models.CharField(max_length=50, verbose_name='Hakkımızda Video Buton Üzerindeki Yazı')),
                ('images_image1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Hakkımızda Resimler Resim1')),
                ('images_image1_content', models.CharField(max_length=50, verbose_name='Hakkımızda Resimler Resim1 açıklaması')),
                ('images_image2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Hakkımızda Resimler Resim2')),
                ('images_image2_content', models.CharField(max_length=50, verbose_name='Hakkımızda Resimler Resim2 açıklaması')),
                ('images_image3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Hakkımızda Resimler Resim3')),
                ('images_image3_content', models.CharField(max_length=50, verbose_name='Hakkımızda Resimler Resim3 açıklaması')),
                ('images_image4', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Hakkımızda Resimler Resim4')),
                ('images_image4_content', models.CharField(max_length=50, verbose_name='Hakkımızda Resimler Resim4 açıklaması')),
                ('middle_title', models.CharField(blank=True, max_length=50, verbose_name='Hakkımızda Footer Üstü Başlık')),
                ('middle_content', models.CharField(blank=True, max_length=100, verbose_name='Hakkımızda Footer Üstü İçerik')),
                ('middle_image1', models.ImageField(blank=True, upload_to='', verbose_name='Hakkımızda Footer Üstü Resim')),
                ('middle_image1_content', models.CharField(blank=True, max_length=50, verbose_name='Hakkımızda Footer Üstü Resim Açıklaması')),
                ('middle_image2', models.ImageField(blank=True, upload_to='', verbose_name='Hakkımızda Footer Üstü Resim')),
                ('middle_image2_content', models.CharField(blank=True, max_length=50, verbose_name='Hakkımızda Footer Üstü Resim Açıklaması')),
            ],
            options={
                'verbose_name': 'Hakkımızda İçerik',
                'verbose_name_plural': 'Hakkımızda İçerikler',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='İSİM:')),
                ('email', models.EmailField(max_length=254, verbose_name='Eposta adresi:')),
                ('message', models.TextField(verbose_name='Mesajınız:')),
            ],
            options={
                'verbose_name': 'Gelen Mesaj',
                'verbose_name_plural': 'Gelen Mesajlar',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Başlık')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('herocontent', models.CharField(max_length=150, verbose_name='Slayt içindeki yazı')),
                ('subherocontent', models.CharField(blank=True, max_length=150, verbose_name='Slayt içindeki alt yazı')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='resim')),
                ('pagemaintitle', models.CharField(max_length=150, verbose_name='Ana sayfa ana başlığı')),
                ('pagesubcontent', models.CharField(blank=True, max_length=150, verbose_name='Ana sayfa alt içerik')),
                ('below_title', models.CharField(blank=True, max_length=150, verbose_name='Alt Başlık')),
                ('below_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Alt Resim')),
                ('below_content', models.CharField(blank=True, max_length=200, verbose_name='Alt içerik')),
                ('last_title', models.CharField(blank=True, max_length=75, verbose_name='En Alt Başlık')),
                ('last_image1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='En Alt Resim')),
                ('last_image2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='En Alt Resim')),
                ('last_content', models.CharField(blank=True, max_length=200, verbose_name='En Alt içerik')),
                ('description', models.CharField(max_length=120, verbose_name='Sayfanın search engine açıklaması')),
                ('is_navbar', models.BooleanField(default=True, verbose_name='Navbarda gösterilsin mi?')),
                ('active', models.BooleanField(default=True, verbose_name='Sitede gösterilsin mi?')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Sıralama')),
                ('is_dropdown', models.BooleanField(default=False, verbose_name='Alt başlıkları olsun mu')),
            ],
            options={
                'verbose_name': 'AnaSayfa Ana İçerikler ',
                'verbose_name_plural': 'AnaSayfa Ana İçerik ',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Başlık')),
                ('content', ckeditor.fields.RichTextField(verbose_name='İçerik')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='resim')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Sıralama')),
                ('active', models.BooleanField(default=True, verbose_name='Sitede gösterilsin mi?')),
            ],
            options={
                'verbose_name': 'Anasayfa Detay',
                'verbose_name_plural': 'Anasayfa Detaylar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeFooterUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Başlık')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Sıralama')),
                ('active', models.BooleanField(default=True, verbose_name='Sitede gösterilsin mi?')),
                ('content1', models.CharField(blank=True, max_length=75, verbose_name='İçerik1')),
                ('content2', models.CharField(blank=True, max_length=75, verbose_name='İçerik2')),
                ('content3', models.CharField(blank=True, max_length=75, verbose_name='İçerik3')),
                ('content4', models.CharField(blank=True, max_length=75, verbose_name='İçerik4')),
                ('content5', models.CharField(blank=True, max_length=75, verbose_name='İçerik5')),
                ('content6', models.CharField(blank=True, max_length=75, verbose_name='İçerik6')),
                ('rightcontent', models.CharField(blank=True, max_length=75, verbose_name='Sağiçerik')),
            ],
            options={
                'verbose_name': 'Anasayfa Footer Üstü Kart',
                'verbose_name_plural': 'Anasayfa Footer Üstü Kartlar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeMiddleHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name=' Başlık')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name=' Resim')),
                ('content', models.CharField(blank=True, max_length=250, verbose_name=' Başlık içerik')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Sıralama')),
                ('active', models.BooleanField(default=True, verbose_name='Sitede gösterilsin mi?')),
            ],
            options={
                'verbose_name': 'Ana Sayfa Orta Alan Başlık',
                'verbose_name_plural': 'Ana Sayfa Orta Alan Başlıklar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='İcon adı')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Ürünlerimiz Başlık')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Ürünlerimiz Sayfa Resim')),
                ('content', ckeditor.fields.RichTextField(blank=True, max_length=250, verbose_name=' Ürünlerimiz içerik')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Ana Başlık')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Ana Resim')),
                ('card1_title', models.CharField(max_length=50, verbose_name='Hizmetler Başlık')),
                ('card1_content', ckeditor.fields.RichTextField(verbose_name='Hizmetler Açıklama')),
                ('card1_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Hizmetler Resim')),
                ('card1_image_cont', models.CharField(max_length=50, verbose_name='Hizmetler Resim Açıklaması')),
                ('card2_title', models.CharField(max_length=50, verbose_name='Hizmetler Başlık')),
                ('card2_content', ckeditor.fields.RichTextField(verbose_name='Hizmetler Açıklama')),
                ('card2_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Hizmetler Resim')),
                ('card2_image_cont', models.CharField(max_length=50, verbose_name='Hizmetler Resim Açıklaması')),
            ],
            options={
                'verbose_name': 'Hizmetler İçerik',
                'verbose_name_plural': 'Hizmetler İçerikler',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('description', models.CharField(max_length=150, verbose_name="Google'da çıkacak olan yazı")),
                ('keywords', models.CharField(max_length=150, verbose_name="Google'da aramalarda çıkabilmek için gerekli anahtar kelimler")),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('copyright_name', models.CharField(default='KaanFilo', max_length=50)),
                ('adress', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('phone2', models.CharField(max_length=20)),
                ('whatsapp_phone', models.CharField(default='', max_length=20)),
                ('navmessage', models.CharField(blank=True, max_length=75, verbose_name='Site en üstünde verilecek mesaj')),
                ('logo1', models.ImageField(default='Rasyonel Dental', upload_to='setting/', verbose_name='logo1')),
                ('logo2', models.ImageField(default='Rasyonel Dental', upload_to='setting/', verbose_name='logo2')),
                ('contact_page_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='İletişim Sayfası Ana Resim')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Favicon resim')),
                ('googleMap', models.CharField(blank=True, max_length=200, null=True, verbose_name='Googlemap iframe')),
                ('contactmessage', models.CharField(blank=True, max_length=150, verbose_name='İletişim mesajı')),
            ],
            options={
                'verbose_name': 'Ayar',
                'verbose_name_plural': 'Ayarlar',
            },
        ),
        migrations.CreateModel(
            name='ProductContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Ürün Başlık')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Ürün Resim')),
                ('image_def', models.CharField(blank=True, max_length=50, verbose_name='Ürün Resim Açıklaması')),
                ('content', ckeditor.fields.RichTextField(blank=True, max_length=250, verbose_name=' Ürün içerik')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aboutcontent', to='pages.producttitle')),
            ],
            options={
                'verbose_name': 'Ürün Bilgi',
                'verbose_name_plural': 'Ürün Bilgiler',
            },
        ),
        migrations.CreateModel(
            name='HomeMiddleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Başlık')),
                ('content', ckeditor.fields.RichTextField(verbose_name='İçerik')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Sıralama')),
                ('active', models.BooleanField(default=True, verbose_name='Sitede gösterilsin mi?')),
                ('header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.homemiddleheader')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.icon')),
            ],
            options={
                'verbose_name': 'Ana Sayfa Orta Alan Detay',
                'verbose_name_plural': 'Ana Sayfa Orta Alan Detaylar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Başlık')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Sıralama')),
                ('active', models.BooleanField(default=True, verbose_name='Sitede gösterilsin mi?')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.icon')),
            ],
            options={
                'verbose_name': 'Anasayfa Alt İcon',
                'verbose_name_plural': 'Anasayfa Alt İconlar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Hakkımızda Başlık')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Hakkımızda Resim')),
                ('content', ckeditor.fields.RichTextField(blank=True, max_length=250, verbose_name=' Hakkımızda içerik')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aboutcontent', to='pages.about')),
            ],
            options={
                'verbose_name': 'Hakkımızda Bilgi',
                'verbose_name_plural': 'Hakkımızda Bilgiler',
            },
        ),
    ]
