# Generated by Django 3.1.6 on 2021-03-14 18:43

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Başlık')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('herocontent', models.CharField(max_length=150, verbose_name='Slayt içindeki yazı')),
                ('subherocontent', models.CharField(blank=True, max_length=150, verbose_name='Slayt içindeki yazı')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='resim')),
                ('pagemaintitle', models.CharField(max_length=150, verbose_name='Ana sayfa ana başlığı')),
                ('pagesubcontent', models.CharField(blank=True, max_length=150, verbose_name='Ana sayfa alt içerik')),
                ('below_title', models.CharField(blank=True, max_length=150, verbose_name='Alt Başlık')),
                ('below_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Alt Resim')),
                ('below_content', models.CharField(blank=True, max_length=150, verbose_name='Alt içerik')),
                ('last_title', models.CharField(blank=True, max_length=150, verbose_name='En Alt Başlık')),
                ('last_image1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='En Alt Resim')),
                ('last_image2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='En Alt Resim')),
                ('last_content', models.CharField(blank=True, max_length=150, verbose_name='En Alt içerik')),
                ('description', models.CharField(max_length=120, verbose_name='Sayfanın search engine açıklaması')),
                ('is_navbar', models.BooleanField(default=True, verbose_name='Navbarda gösterilsin mi?')),
                ('active', models.BooleanField(default=True, verbose_name='Sitede gösterilsin mi?')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Sıralama')),
                ('is_dropdown', models.BooleanField(default=False, verbose_name='Alt başlıkları olsun mu')),
            ],
            options={
                'verbose_name': 'Başlık',
                'verbose_name_plural': 'Başlıklar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Başlık')),
                ('content', ckeditor.fields.RichTextField(verbose_name='İçerik')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='resim')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Sıralama')),
                ('active', models.BooleanField(default=True, verbose_name='Sitede gösterilsin mi?')),
            ],
            options={
                'verbose_name': 'Anasayfa Detay',
                'verbose_name_plural': 'Anasayfa Detaylar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeFooterUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Başlık')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Sıralama')),
                ('active', models.BooleanField(default=True, verbose_name='Sitede gösterilsin mi?')),
                ('content', models.CharField(max_length=75, verbose_name='İçerik3')),
            ],
            options={
                'verbose_name': 'Anasayfa Footer Üstü Kart',
                'verbose_name_plural': 'Anasayfa Footer Üstü Kartlar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeMiddleHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name=' Başlık')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name=' Resim')),
                ('content', models.CharField(blank=True, max_length=250, verbose_name=' Başlık içerik')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Sıralama')),
                ('active', models.BooleanField(default=True, verbose_name='Sitede gösterilsin mi?')),
            ],
            options={
                'verbose_name': 'Orta Sayfa Başlık',
                'verbose_name_plural': 'Orta Sayfa başlıklar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='İcon adı')),
            ],
        ),
        migrations.CreateModel(
            name='HomeMiddleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Başlık')),
                ('content', ckeditor.fields.RichTextField(verbose_name='İçerik')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Sıralama')),
                ('active', models.BooleanField(default=True, verbose_name='Sitede gösterilsin mi?')),
                ('header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.homemiddleheader')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.icon')),
            ],
            options={
                'verbose_name': 'Anasayfa Detay',
                'verbose_name_plural': 'Anasayfa Detaylar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Başlık')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Sıralama')),
                ('active', models.BooleanField(default=True, verbose_name='Sitede gösterilsin mi?')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.icon')),
            ],
            options={
                'verbose_name': 'Anasayfa Alt İcon',
                'verbose_name_plural': 'Anasayfa Alt İconlar',
                'ordering': ['order'],
            },
        ),
    ]
