# Generated by Django 3.1.6 on 2021-03-06 18:03

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ekstra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Başlık')),
            ],
        ),
        migrations.CreateModel(
            name='EkstraContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='başlık')),
                ('short_content', models.CharField(max_length=75, verbose_name='kısa açıklama')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='resim')),
                ('ekstra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.ekstra')),
            ],
        ),
        migrations.CreateModel(
            name='EkstraType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Başlık')),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Başlık')),
                ('slug', models.SlugField(default='', editable=False, verbose_name='site')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('content', ckeditor.fields.RichTextField(verbose_name='İçeirk')),
                ('description', models.CharField(max_length=120, verbose_name='Sayfanın search engine açıklaması')),
                ('is_navbar', models.BooleanField(default=True, verbose_name='Navbarda gösterilsin mi?')),
                ('active', models.BooleanField(default=True, verbose_name='Sitede gösterilsin mi?')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Sıralama')),
                ('is_dropdown', models.BooleanField(default=False, verbose_name='Alt başlıkları olsun mu')),
                ('ekstras', models.ManyToManyField(blank=True, null=True, to='pages.Ekstra')),
            ],
            options={
                'verbose_name': 'Başlık',
                'verbose_name_plural': 'Başlıklar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='İcon adı')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='html template')),
                ('ekstras', models.ManyToManyField(blank=True, null=True, to='pages.EkstraContent')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, unique=True, verbose_name='Başlık')),
                ('slug', models.SlugField(editable=False, verbose_name='site')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('description', models.CharField(max_length=120, verbose_name='Sayfanın search engine açıklaması')),
                ('keywords', models.CharField(max_length=120, verbose_name='Sayfanın search engine anahtar kelimeleri')),
                ('active', models.BooleanField(default=True, verbose_name='Sitede gösterilsin mi?')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Sıralama')),
                ('short_content', models.CharField(max_length=75, verbose_name='Kısa Açıklama')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Açıklama')),
                ('header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='pages.header')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.icon')),
            ],
        ),
        migrations.AddField(
            model_name='header',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.template'),
        ),
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='resim')),
                ('short_description', models.CharField(max_length=75, verbose_name='Kısa açıklama')),
                ('content', models.TextField(verbose_name='Açıklama')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.page')),
            ],
        ),
        migrations.AddField(
            model_name='ekstracontent',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.icon'),
        ),
        migrations.AddField(
            model_name='ekstra',
            name='ekstra_tipi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.ekstratype'),
        ),
    ]
