# Generated by Django 3.1.6 on 2021-02-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='slug',
            field=models.SlugField(default='a', editable=False, verbose_name='site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(default='a', editable=False, verbose_name='site'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=75, unique=True, verbose_name='Başlık'),
        ),
    ]
