# Generated by Django 3.1.6 on 2021-03-14 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'ordering': ['order'], 'verbose_name': 'Anasayfa ', 'verbose_name_plural': 'Anasayfa '},
        ),
        migrations.AlterModelOptions(
            name='homemiddledetail',
            options={'ordering': ['order'], 'verbose_name': 'Ana Sayfa Orta Alan Detay', 'verbose_name_plural': 'Ana Sayfa Orta Alan Detaylar'},
        ),
        migrations.AlterModelOptions(
            name='homemiddleheader',
            options={'ordering': ['order'], 'verbose_name': 'Ana Sayfa Orta Alan Başlık', 'verbose_name_plural': 'Ana Sayfa Orta Alan Başlıklar'},
        ),
    ]
