# Generated by Django 3.1.6 on 2021-03-06 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='ekstras',
        ),
    ]
