# Generated by Django 3.1.6 on 2021-03-18 09:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcontent',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name=' Ürün içerik'),
        ),
    ]
