# Generated by Django 3.1.6 on 2021-02-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210220_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='slug',
            field=models.SlugField(default='', editable=False, verbose_name='site'),
        ),
    ]
