# Generated by Django 3.1.6 on 2021-03-14 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210314_2246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'ordering': ['order'], 'verbose_name': 'Herbir Sayfa Ortak Girdi ', 'verbose_name_plural': 'Herbir Sayfa Ortak Girdiler '},
        ),
    ]
