# Generated by Django 3.1.6 on 2021-02-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210220_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='is_dropdown',
            field=models.BooleanField(default=False, verbose_name='Sitede gösterilsin mi?'),
        ),
    ]
