# Generated by Django 3.1.6 on 2021-03-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210314_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='İsim Soy:')),
                ('email', models.EmailField(max_length=254, verbose_name='Eposta adresi:')),
                ('message', models.TextField(verbose_name='Mesajınız:')),
            ],
            options={
                'verbose_name': 'Gelen Mesaj',
                'verbose_name_plural': 'Gelen Mesajlar',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('description', models.CharField(max_length=150, verbose_name="Google'da çıkacak olan yazı")),
                ('keywords', models.CharField(max_length=150, verbose_name="Google'da aramalarda çıkabilmek için gerekli anahtar kelimler")),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('copyright_name', models.CharField(default='KaanFilo', max_length=50)),
                ('adress', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('phone2', models.CharField(max_length=20)),
                ('whatsapp_phone', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Hakkımızda kısmı için resim')),
                ('content', models.TextField(verbose_name='Hakkımızda kısmı için içerik:')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Favicon resim')),
                ('googleMap', models.CharField(blank=True, max_length=200, null=True, verbose_name='Googlemap iframe')),
            ],
            options={
                'verbose_name': 'Ayar',
                'verbose_name_plural': 'Ayarlar',
            },
        ),
        migrations.AlterField(
            model_name='home',
            name='subherocontent',
            field=models.CharField(blank=True, max_length=150, verbose_name='Slayt içindeki alt yazı'),
        ),
    ]
