# Generated by Django 3.1.6 on 2021-03-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20210315_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homefooterup',
            name='content',
        ),
        migrations.AddField(
            model_name='homefooterup',
            name='content1',
            field=models.CharField(blank=True, max_length=75, verbose_name='İçerik1'),
        ),
        migrations.AddField(
            model_name='homefooterup',
            name='content2',
            field=models.CharField(blank=True, max_length=75, verbose_name='İçerik2'),
        ),
        migrations.AddField(
            model_name='homefooterup',
            name='content3',
            field=models.CharField(blank=True, max_length=75, verbose_name='İçerik3'),
        ),
        migrations.AddField(
            model_name='homefooterup',
            name='content4',
            field=models.CharField(blank=True, max_length=75, verbose_name='İçerik4'),
        ),
        migrations.AddField(
            model_name='homefooterup',
            name='content5',
            field=models.CharField(blank=True, max_length=75, verbose_name='İçerik5'),
        ),
        migrations.AddField(
            model_name='homefooterup',
            name='content6',
            field=models.CharField(blank=True, max_length=75, verbose_name='İçerik6'),
        ),
    ]
