# Generated by Django 3.1.6 on 2021-02-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_header_is_dropdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='is_dropdown',
            field=models.BooleanField(default=False, verbose_name='Alt başlıkları olsun mu'),
        ),
    ]
