# Generated by Django 3.1.6 on 2021-03-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20210321_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='description',
            field=models.CharField(max_length=150, verbose_name="İletişim Sayfası için Google'da çıkacak olan yazı"),
        ),
        migrations.AlterField(
            model_name='setting',
            name='keywords',
            field=models.CharField(max_length=150, verbose_name=" İletişim Sayfası için Google'da aramalarda çıkabilmek için gerekli anahtar kelimler"),
        ),
    ]
