# Generated by Django 3.1.6 on 2021-03-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20210315_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='homefooterup',
            name='rightcontent',
            field=models.CharField(blank=True, max_length=75, verbose_name='İçerik6'),
        ),
    ]
