# Generated by Django 3.1.6 on 2021-02-20 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20210220_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='header',
            options={'ordering': ['order'], 'verbose_name': 'Başlık', 'verbose_name_plural': 'Başlıklar'},
        ),
    ]
