# Generated by Django 3.1.6 on 2021-03-18 08:58

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_homefooterup_rightcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=50, verbose_name='Hakkımızda Resim Ortası Başlık')),
                ('about_main_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Hakkımızda Ana Resim')),
                ('images_title', models.CharField(max_length=50, verbose_name='Hakkımızda Resimler Başlık')),
                ('images_content', models.TextField(max_length=50, verbose_name='Hakkımızda Resimler İçerik')),
                ('youtube_url', models.URLField(verbose_name='Hakkımızda Video Linki')),
                ('button_name', models.CharField(max_length=50, verbose_name='Hakkımızda Video Buton Üzerindeki Yazı')),
                ('images_image1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Hakkımızda Resimler Resim1')),
                ('images_image1_content', models.CharField(max_length=50, verbose_name='Hakkımızda Resimler Resim1 açıklaması')),
                ('images_image2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Hakkımızda Resimler Resim2')),
                ('images_image2_content', models.CharField(max_length=50, verbose_name='Hakkımızda Resimler Resim2 açıklaması')),
                ('images_image3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Hakkımızda Resimler Resim3')),
                ('images_image3_content', models.CharField(max_length=50, verbose_name='Hakkımızda Resimler Resim3 açıklaması')),
                ('images_image4', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Hakkımızda Resimler Resim4')),
                ('images_image4_content', models.CharField(max_length=50, verbose_name='Hakkımızda Resimler Resim4 açıklaması')),
                ('middle_title', models.CharField(blank=True, max_length=50, verbose_name='Hakkımızda Footer Üstü Başlık')),
                ('middle_content', models.CharField(blank=True, max_length=100, verbose_name='Hakkımızda Footer Üstü İçerik')),
                ('middle_image1', models.ImageField(blank=True, upload_to='', verbose_name='Hakkımızda Footer Üstü Resim')),
                ('middle_image1_content', models.CharField(blank=True, max_length=50, verbose_name='Hakkımızda Footer Üstü Resim Açıklaması')),
                ('middle_image2', models.ImageField(blank=True, upload_to='', verbose_name='Hakkımızda Footer Üstü Resim')),
                ('middle_image2_content', models.CharField(blank=True, max_length=50, verbose_name='Hakkımızda Footer Üstü Resim Açıklaması')),
            ],
            options={
                'verbose_name': 'Hakkımızda İçerik',
                'verbose_name_plural': 'Hakkımızda İçerikler',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Ana Başlık')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Ana Resim')),
                ('card1_title', models.CharField(max_length=50, verbose_name='Hizmetler Başlık')),
                ('card1_content', ckeditor.fields.RichTextField(verbose_name='Hizmetler Açıklama')),
                ('card1_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Hizmetler Resim')),
                ('card1_image_cont', models.CharField(max_length=50, verbose_name='Hizmetler Resim Açıklaması')),
                ('card2_title', models.CharField(max_length=50, verbose_name='Hizmetler Başlık')),
                ('card2_content', ckeditor.fields.RichTextField(verbose_name='Hizmetler Açıklama')),
                ('card2_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Hizmetler Resim')),
                ('card2_image_cont', models.CharField(max_length=50, verbose_name='Hizmetler Resim Açıklaması')),
            ],
            options={
                'verbose_name': 'Hizmetler İçerik',
                'verbose_name_plural': 'Hizmetler İçerikler',
            },
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'ordering': ['order'], 'verbose_name': 'AnaSayfa Ana İçerikler ', 'verbose_name_plural': 'AnaSayfa Ana İçerik '},
        ),
        migrations.RemoveField(
            model_name='setting',
            name='content',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='image',
        ),
        migrations.AddField(
            model_name='setting',
            name='contact_page_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='İletişim Sayfası Ana Resim'),
        ),
        migrations.AddField(
            model_name='setting',
            name='contactmessage',
            field=models.CharField(blank=True, max_length=150, verbose_name='İletişim mesajı'),
        ),
        migrations.AddField(
            model_name='setting',
            name='logo1',
            field=models.ImageField(default='Rasyonel Dental', upload_to='setting/', verbose_name='logo1'),
        ),
        migrations.AddField(
            model_name='setting',
            name='logo2',
            field=models.ImageField(default='Rasyonel Dental', upload_to='setting/', verbose_name='logo2'),
        ),
        migrations.AddField(
            model_name='setting',
            name='navmessage',
            field=models.CharField(blank=True, max_length=75, verbose_name='Site en üstünde verilecek mesaj'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='name',
            field=models.CharField(max_length=30, verbose_name='İSİM:'),
        ),
        migrations.AlterField(
            model_name='home',
            name='below_content',
            field=models.CharField(blank=True, max_length=200, verbose_name='Alt içerik'),
        ),
        migrations.AlterField(
            model_name='home',
            name='last_content',
            field=models.CharField(blank=True, max_length=200, verbose_name='En Alt içerik'),
        ),
        migrations.AlterField(
            model_name='home',
            name='last_title',
            field=models.CharField(blank=True, max_length=75, verbose_name='En Alt Başlık'),
        ),
        migrations.AlterField(
            model_name='homefooterup',
            name='rightcontent',
            field=models.CharField(blank=True, max_length=75, verbose_name='Sağiçerik'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='whatsapp_phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Hakkımızda Başlık')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Hakkımızda Resim')),
                ('content', ckeditor.fields.RichTextField(blank=True, max_length=250, verbose_name=' Hakkımızda içerik')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aboutcontent', to='pages.about')),
            ],
            options={
                'verbose_name': 'Hakkımızda Bilgi',
                'verbose_name_plural': 'Hakkımızda Bilgiler',
            },
        ),
    ]
