# Generated by Django 3.1.6 on 2021-03-21 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20210321_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homemiddledetail',
            name='icon',
        ),
        migrations.DeleteModel(
            name='HomeIcon',
        ),
        migrations.DeleteModel(
            name='Icon',
        ),
    ]
