# Generated by Django 3.1.6 on 2021-02-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20210220_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='EkstraContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='html template')),
                ('short_content', models.CharField(max_length=75, verbose_name='html template')),
            ],
        ),
        migrations.AddField(
            model_name='template',
            name='ekstras',
            field=models.ManyToManyField(null='blank', to='pages.EkstraContent'),
            preserve_default='blank',
        ),
    ]
