# Generated by Django 3.1.6 on 2021-03-21 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20210321_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homedetail',
            options={'ordering': ['order'], 'verbose_name': 'Anasayfa Şerit İçerik', 'verbose_name_plural': 'Anasayfa Şerit İçerikler'},
        ),
    ]
