# Generated by Django 3.1.6 on 2021-03-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20210315_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='content',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='image',
        ),
        migrations.AddField(
            model_name='setting',
            name='contactmessage',
            field=models.CharField(blank=True, max_length=150, verbose_name='İletişim mesajı'),
        ),
    ]
