# Generated by Django 3.1.6 on 2021-03-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20210315_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Sitede gösterilsin mi?'),
        ),
    ]
