# Generated by Django 3.1.6 on 2021-03-21 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20210321_2035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homemiddleheader',
            options={'ordering': ['order'], 'verbose_name': 'Ana Sayfa Orta Alan İçerik', 'verbose_name_plural': 'Ana Sayfa Orta Alan İçerikler'},
        ),
    ]
