# Generated by Django 3.1.6 on 2021-02-20 17:38

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20210220_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='İcon adı')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='content',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Açıklama'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='short_content',
            field=models.CharField(default=1, max_length=75, verbose_name='Kısa Açıklama'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='template',
            name='ekstras',
            field=models.ManyToManyField(blank=True, null=True, to='pages.EkstraContent'),
        ),
        migrations.AddField(
            model_name='page',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.icon'),
        ),
    ]
