# Generated by Django 3.1.6 on 2021-02-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20210220_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ekstra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='html template')),
                ('ekstra_contents', models.ManyToManyField(blank=True, null=True, to='pages.EkstraContent')),
            ],
        ),
        migrations.AddField(
            model_name='header',
            name='ekstras',
            field=models.ManyToManyField(blank=True, null=True, to='pages.Ekstra'),
        ),
    ]
