# Generated by Django 3.1.6 on 2021-03-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20210321_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttitle',
            name='product_title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ürünlerimiz Başlık'),
        ),
    ]
