# Generated by Django 3.1.6 on 2021-03-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_contactinfo_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=50, verbose_name='Hakkımızda Resim Ortası Başlık')),
                ('about_main_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Hakkımızda Ana Resim')),
                ('images_title', models.CharField(max_length=50, verbose_name='Hakkımızda Resimler Başlık')),
                ('images_content', models.CharField(max_length=50, verbose_name='Hakkımızda Resimler İçerik')),
                ('images_image1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Hakkımızda Resimler Resim1')),
                ('images_image1_content', models.CharField(max_length=50, verbose_name='Hakkımızda Resimler Resim1 açıklaması')),
                ('images_image2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Hakkımızda Resimler Resim2')),
                ('images_image2_content', models.CharField(max_length=50, verbose_name='Hakkımızda Resimler Resim2 açıklaması')),
                ('images_image3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Hakkımızda Resimler Resim3')),
                ('images_image3_content', models.CharField(max_length=50, verbose_name='Hakkımızda Resimler Resim3 açıklaması')),
                ('images_image4', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Hakkımızda Resimler Resim4')),
                ('images_image4_content', models.CharField(max_length=50, verbose_name='Hakkımızda Resimler Resim4 açıklaması')),
            ],
            options={
                'verbose_name': 'Hakkımızda İçerik',
                'verbose_name_plural': 'Hakkımızda İçerikler',
            },
        ),
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Hakkımızda Başlık')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Hakkımızda Resim')),
                ('content', models.CharField(blank=True, max_length=250, verbose_name=' Hakkımızda içerik')),
            ],
            options={
                'verbose_name': 'Hakkımızda Bilgi',
                'verbose_name_plural': 'Hakkımızda Bilgiler',
            },
        ),
    ]
