# Generated by Django 3.1.6 on 2021-02-20 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20210220_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='ekstracontent',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.icon'),
        ),
        migrations.AddField(
            model_name='ekstracontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='resim'),
        ),
        migrations.AlterField(
            model_name='ekstracontent',
            name='title',
            field=models.CharField(max_length=50, verbose_name='başlık'),
        ),
    ]
