# Generated by Django 3.1.6 on 2021-03-21 17:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_producttitle_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttitle',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name=' Ürünlerimiz içerik'),
        ),
        migrations.AlterField(
            model_name='producttitle',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Ürünlerimiz Resim üzeri Başlık'),
        ),
    ]
