# Generated by Django 3.1.6 on 2021-03-23 09:37

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20210321_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttitle',
            name='title_color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
