# Generated by Django 3.1.6 on 2021-02-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20210220_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='ekstra',
            name='html_code',
            field=models.TextField(default=1, verbose_name='Html kodu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ekstracontent',
            name='short_content',
            field=models.CharField(max_length=75, verbose_name='kısa açıklama'),
        ),
    ]
