# Generated by Django 3.1.6 on 2021-02-20 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20210220_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='EkstraType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='html template')),
            ],
        ),
        migrations.AddField(
            model_name='ekstra',
            name='ekstra_tipi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.ekstratype'),
        ),
    ]
