# Generated by Django 3.1.6 on 2021-03-23 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_remove_producttitle_title_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homemiddleheader',
            options={'ordering': ['order'], 'verbose_name': 'Ana Sayfa ikinci Alan İçerik', 'verbose_name_plural': 'Ana Sayfa ikinci  Alan İçerikler'},
        ),
    ]
