# Generated by Django 3.1.6 on 2021-02-20 19:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20210220_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='İçeirk'),
        ),
    ]
