# Generated by Django 3.1.6 on 2021-03-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20210316_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='button_name',
            field=models.CharField(default=1, max_length=50, verbose_name='Hakkımızda Video Buton Üzerindeki Yazı'),
            preserve_default=False,
        ),
    ]
