# Generated by Django 3.1.6 on 2021-03-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_about_button_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='middle_content',
            field=models.CharField(blank=True, max_length=100, verbose_name='Hakkımızda Footer Üstü İçerik'),
        ),
        migrations.AddField(
            model_name='about',
            name='middle_image1',
            field=models.CharField(blank=True, max_length=50, verbose_name='Hakkımızda Resimler Başlık'),
        ),
        migrations.AddField(
            model_name='about',
            name='middle_image2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Hakkımızda Resimler Başlık'),
        ),
        migrations.AddField(
            model_name='about',
            name='middle_title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Hakkımızda Footer Üstü Başlık'),
        ),
    ]
