# Generated by Django 3.1.6 on 2021-03-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20210323_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemiddleheader',
            name='image_def',
            field=models.CharField(blank=True, max_length=50, verbose_name='Resim Açıklaması'),
        ),
    ]
