# Generated by Django 3.1.6 on 2021-03-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20210316_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='middle_image1_content',
            field=models.CharField(blank=True, max_length=50, verbose_name='Hakkımızda Footer Üstü Resim Açıklaması'),
        ),
        migrations.AddField(
            model_name='about',
            name='middle_image2_content',
            field=models.CharField(blank=True, max_length=50, verbose_name='Hakkımızda Footer Üstü Resim Açıklaması'),
        ),
        migrations.AlterField(
            model_name='about',
            name='middle_image1',
            field=models.ImageField(blank=True, max_length=50, upload_to='', verbose_name='Hakkımızda Footer Üstü Resim'),
        ),
        migrations.AlterField(
            model_name='about',
            name='middle_image2',
            field=models.ImageField(blank=True, max_length=50, upload_to='', verbose_name='Hakkımızda Footer Üstü Resim'),
        ),
    ]
