# Generated by Django 3.1.6 on 2021-03-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20210316_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='middle_image1',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Hakkımızda Footer Üstü Resim'),
        ),
        migrations.AlterField(
            model_name='about',
            name='middle_image2',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Hakkımızda Footer Üstü Resim'),
        ),
    ]
