# Generated by Django 3.1.6 on 2021-03-16 20:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_auto_20210316_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Ana Başlık')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Ana Resim')),
                ('card1_title', models.CharField(max_length=50, verbose_name='Hizmetler Başlık')),
                ('card1_content', ckeditor.fields.RichTextField(verbose_name='Hizmetler Açıklama')),
                ('card1_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Hizmetler Resim')),
                ('card1_image_cont', models.CharField(max_length=50, verbose_name='Hizmetler Resim Açıklaması')),
                ('card2_title', models.CharField(max_length=50, verbose_name='Hizmetler Başlık')),
                ('card2_content', ckeditor.fields.RichTextField(verbose_name='Hizmetler Açıklama')),
                ('card2_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Hizmetler Resim')),
                ('card2_image_cont', models.CharField(max_length=50, verbose_name='Hizmetler Resim Açıklaması')),
            ],
            options={
                'verbose_name': 'Hizmetler İçerik',
                'verbose_name_plural': 'Hizmetler İçerikler',
            },
        ),
        migrations.AlterField(
            model_name='about',
            name='images_content',
            field=models.TextField(max_length=50, verbose_name='Hakkımızda Resimler İçerik'),
        ),
    ]
