# Generated by Django 3.1.6 on 2021-03-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20210316_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='navmessage',
            field=models.CharField(default=1, max_length=75, verbose_name='Site en üstünde verilecek mesaj'),
            preserve_default=False,
        ),
    ]
