# Generated by Django 3.1.6 on 2021-03-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_auto_20210317_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='navmessage',
        ),
        migrations.AddField(
            model_name='setting',
            name='logo1',
            field=models.ImageField(default='Rasyonel Dental', upload_to='setting/', verbose_name='logo1'),
        ),
        migrations.AddField(
            model_name='setting',
            name='logo2',
            field=models.ImageField(default='Rasyonel Dental', upload_to='setting/', verbose_name='logo2'),
        ),
        migrations.AddField(
            model_name='setting',
            name='navmessage',
            field=models.CharField(blank=True, max_length=75, verbose_name='Site en üstünde verilecek mesaj'),
        ),
    ]
