# Generated by Django 3.1.6 on 2021-03-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_auto_20210317_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='contact_page_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='İletişim Sayfası Ana Resim'),
        ),
    ]
