# Generated by Django 3.1.6 on 2021-03-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_setting_contact_page_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='whatsapp_phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
