# Generated by Django 3.1.6 on 2021-02-15 13:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Hakkımızda')),
                ('sub_content', models.CharField(max_length=250, verbose_name='hakkımızda alt metin')),
                ('content', ckeditor.fields.RichTextField(verbose_name='içerik')),
                ('about_image', models.ImageField(upload_to='', verbose_name='Hakkımızda kısmında çıkacak olan resim')),
                ('about_youtube_url', models.URLField(verbose_name="Hakkımızda ile ilgili olan youtube URL'i ")),
            ],
            options={
                'verbose_name': 'Hakkımızda',
                'verbose_name_plural': 'Hakkımızdakiler',
            },
        ),
    ]
